obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_V2_MMI) += focaltech_v2_mmi.o
focaltech_v2_mmi-objs += focaltech_core.o
focaltech_v2_mmi-objs += focaltech_ex_fun.o
focaltech_v2_mmi-objs += focaltech_ex_mode.o
focaltech_v2_mmi-objs += focaltech_gesture.o
focaltech_v2_mmi-objs += focaltech_esdcheck.o
focaltech_v2_mmi-objs += focaltech_point_report_check.o
focaltech_v2_mmi-objs += focaltech_flash.o
focaltech_v2_mmi-objs += focaltech_flash/focaltech_upgrade_ft3518u.o
focaltech_v2_mmi-objs += focaltech_flash/focaltech_upgrade_ft5452i.o
focaltech_v2_mmi-objs += focaltech_i2c.o

ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_v2_mmi/include
ccflags-y += -I$(srctree)/drivers/input/touchscreen/focaltech_v2_mmi/focaltech_test

ifneq ($(filter ft3519,$(CONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME)),)
	ccflags-y += -DCONFIG_INPUT_FOCALTECH_0FLASH_MMI_IC_NAME_FT3519
endif

ifneq ($(filter m y,$(CONFIG_INPUT_TOUCHSCREEN_MMI)),)
	ccflags-y += -DCONFIG_INPUT_TOUCHSCREEN_MMI
	focaltech_v2_mmi-objs += focaltech_ts_mmi.o
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_MMI_ENABLE_DOUBLE_TAP)),)
	ccflags-y += -DFOCALTECH_SENSOR_EN
endif
ifneq ($(filter m y,$(CONFIG_INPUT_FOCALTECH_MMI_ENABLE_PALM)),)
	ccflags-y += -DFOCALTECH_PALM_SENSOR_EN
endif

ifneq ($(filter m y, $(CONFIG_DRM_PANEL_NOTIFICATIONS)),)
	ccflags-y += -DCONFIG_DRM_PANEL_NOTIFICATIONS
endif
